### ISSUE TITLE
career support - trello - Trello for jobs

### ISSUE THREAD

**Issue by ktrammell95** [alsleaders/assignments#16]
# Create a Trello card for one job

In this assignment, you will create a Trello card for a job that you found interesting. This can be for your dream job or just something that sounded interesting to you.

## Card Requirements

- [x] Company name - job title
- [x] Description of the company
- [x] Company website link
- [x] Location
- [x] Link to the job description

- Add comments:
- [x] What is their narrative?
- [x] Why do you like this company?
- [x] Why did you like this posting?
- [x] How might you benefit them?

## Turning in your assignment

- To turn in this assignement you will move your card to "Ready for Rec" and tag Katherine (@ktrammellsdg) in a comment on that card with the wording "Ready for a Rec"
- Copy and paste the link to your card as a comment on this issue

## Due Date

- This assignment is due by 9 am on Friday, May 31st.

**Comment by alsleaders** [comment]
https://trello.com/c/0W2ADElq/2-tampa-bay-times-back-end-developer

**Comment by ktrammell95** [comment]
Your homework was marked: **Exceeds Expectations**

![Niiiiiiiiice!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0f7e0d5535291cc82f410da4761392ed248ba5a6/tumblr_inline_odd2x9PvYg1raprkq_400.gif)
> &ldquo;Niiiiiiiiice!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/65)**__
