### ISSUE TITLE
week 05 - day 01 - mineswept

### ISSUE THREAD

**Issue by mdewey** [alsleaders/assignments#17]
# A mine!

This morning we did a couple of code reviews. Take these lessons and finish up your minesweeper apps. 

Also, we have been exploring react for the past week. Let's take those skills and upgrade some old projects. 

## Objectives

- With your new knowledge, finish minesweeper
- Update an old project using React. 

### Explorer Mode

- [x] Finish your minesweeper
- [ ] Go back to project to a project unit-i (week 1 through 3)

### Adventure Mode

- [ ] Work on any previous adventure or epic mode of any previous homework
- [ ] Go back and redo an old project.

**Comment by alsleaders** [comment]
https://github.com/alsleaders/minesweeper

**Comment by alsleaders** [comment]
https://github.com/alsleaders/react-weather.git

I'm sorry, this is definitely not done.  But I'm calling it for the night.

**Comment by alsleaders** [comment]
https://github.com/alsleaders/react-weather.git

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBUdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a60036409d53f8b1c2804766f540dccb4215ec74/giphy-3.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/68)**__
