### ISSUE TITLE
career support - resumes - Build your Resume

### ISSUE THREAD

**Issue by ktrammell95** [alsleaders/assignments#21]
Key areas of Information to include:

## Contact information
- [ ] Email
- [ ] Phone Number (Google numbers are great if you want to protect your personal number)
- [ ] Github link
- [ ] Portfolio link

## Summary 
- [ ]  Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” simply use a headline that encapsulates your credentials.

## Skills 
- [ ]  You’ll want to incorporate the right keywords so that your resume is optimized for application tracking systems

## Professional experience
- [ ]  Focus on your accomplishments rather than your day-to-day responsibilities

## Education
- [ ]  Simply write where you went college and your degree.
- [ ]  It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [ ]  Volunteering and community service

## Due Date: Wednesday, June 19th
- [ ]  Upload or submit a link to your resume for review.

**Comment by alsleaders** [comment]
[ALResumeJune19.pdf](https://github.com/alsleaders/assignments/files/3298175/ALResumeJune19.pdf)

**Comment by ktrammell95** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBWUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa7a355c1c44cd588feef47afca922431993c337/giphy-9.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/74)**__
