### ISSUE TITLE
week 07 - day 01  -  INSERT INTO Student (knowledge) VALUES ('SQL')

### ISSUE THREAD

**Issue by mdewey** [alsleaders/assignments#26]
# INSERT INTO Student (knowledge) VALUES ('SQL')

Every application uses data in some way. This will help you set up your development environment as well as get used to querying databases.

## Objectives

- Install Postgres
- Create a database for Employees
- Write some queries to use the database

## Requirements

- Set up postgres by following [these directions.](https://suncoast.io/handbook/tools/postgresql/)

### Explorer Mode

- [x] Install Postgres
- [x] Create a database: `company_database`
- [x] Create a table: `employees`
- [x] Add the following columns to the table, Use your best judgement for data types

  - full_name
  - salary
  - job_position
  - phone_extension
  - part_time

- [x] Create queries that can do the following:

  - [x] Select all columns for all employees
  - [x] Select only the Full Name and Phone Extension for only Full Time employees
  - [x] Insert a new part time employee, as a software developer, part time, with a salary of 450
  - [x] Update all employees that are the cooks to have a salary of 500
  - [x] Delete all employees that have the full name of "Lazy Lynn"
  - [x] Update all employees to be full time
  - [x] Add a column to the table: `parking_spot_number` as a string that up to 10 characters long

- [x] Turn in the above queries as a gist

### Adventure Mode

- [ ] Work on your final project

### Epic Mode

- [ ] Investigate working with C# and Postgres, HINT: `entity framework core`

## Additional Resources

- [PostgreSQL 10 Documentation](https://www.postgresql.org/docs/10/static/index.html)

## Recommended Practice:

- For more practice, Hackerrank has a [SQL Track](https://www.hackerrank.com/domains/sql)

**Comment by alsleaders** [comment]
https://gist.github.com/alsleaders/071819b32c8167e034f5523e9ec724a5

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBWdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3921363294f2f54e76ec6fe9deb21cb56ace25a8/giphy-11.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/76)**__
